name: Trigger auto deployment for springb2cnickcapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/springb2cnickcapp-AutoDeployTrigger-ce212f67-4297-4b76-ae60-c07577bb80e8.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: springb2cnickreg.azurecr.io
          username: ${{ secrets.SPRINGB2CNICKCAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.SPRINGB2CNICKCAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: springb2cnickreg.azurecr.io/hello:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SPRINGB2CNICKCAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n springb2cnickcapp -g springb2c-demo-nick --server springb2cnickreg.azurecr.io --username  ${{ secrets.SPRINGB2CNICKCAPP_REGISTRY_USERNAME }} --password ${{ secrets.SPRINGB2CNICKCAPP_REGISTRY_PASSWORD }}
            az containerapp update -n springb2cnickcapp -g springb2c-demo-nick --image springb2cnickreg.azurecr.io/hello:${{ github.sha }}
